### ISSUE TITLE
responseAllocHTMLWithStatus() ignoring status code

### ISSUE THREAD

**Issue by braddabug** [hellerf/EmbeddableWebServer#1]
Several functions like responseAllocHTMLWithStatus() are ignoring the status code parameter and always using 200. This is breaking functions like responseAlloc404NotFoundHTML(). The browser always gets 200 OK rather than the actual response code.

**Comment by hellerf** [comment]
A bug report! This is exciting! Thanks braddabug. I see exactly what you're talking about. I've pushed commit 1451d9b92452a0cfa0be64ec298cba42cd5ed818 to master. 

EDIT: Let me know if this fix works for you.

**Comment by hellerf** [comment]
I'm closing this bug report
