### ISSUE TITLE
An improper locking bug(e.g., deadlock) on the lock server

### ISSUE THREAD

**Issue by ycaibb** [hellerf/EmbeddableWebServer#10]
Hi, developers, thank you for your checking. I found a possible bug in UltraGrid, which locates in `EmbeddableWebServer`.
It seems the lock `server` is not released correctly when` !server->initialize` in the function `serverStop`?

https://github.com/CESNET/UltraGrid/blob/e3c926c8ff67586bf74c4cc0763a78c83ede9cf6/src/EmbeddableWebServer.h#L1515-L1526
Can you confirm this?

The original issue:
https://github.com/CESNET/UltraGrid/issues/183

**Comment by ycaibb** [comment]
My problem has been resolved.

**Comment by hellerf** [comment]
Oh that certainly does look extremely suspicious! Thank you for reporting it
